name: ansible-base Image CI

on: workflow_dispatch

env:
  IMAGE_PREFIX: xcbeyond
  IMAGE_NAME: ansible-base
  IMAGE_VERSION: v2.14.6
  

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login dockerhub registry
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u xcbeyond --password-stdin

    # - name: Build image
    #   run: docker build . --file ./$IMAGE_NAME/Dockerfile --tag $IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_VERSION 

    # - name: Push image
    #   run: |
    #     docker image tag $IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_VERSION $IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_VERSION
    #     docker push $IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_VERSION

    - name: Build & push image
      run: docker buildx build --push --platform linux/amd64,linux/arm64 . --file ./$IMAGE_NAME/Dockerfile --tag $IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_VERSION