name: oraclelinux-instantclient Image CI

on: workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: image=moby/buildkit:v0.11.0
    
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: oraclelinux-instantclient
        tag: 19.10
        registry: ghcr.io
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        overrideDriver: true
        dockerfile: ./oraclelinux-instantclient/Dockerfile
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}